plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.5'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'org.internetstore'
version = '0.0.1-SNAPSHOT'
description = 'scooters-rent-application'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'io.jsonwebtoken:jjwt-api:0.12.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.5'
    testImplementation 'org.springframework.security:spring-security-test'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'me.paulschwarz:spring-dotenv:4.0.0'

    runtimeOnly 'org.postgresql:postgresql'

    implementation 'org.springframework.boot:spring-boot-starter'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // Location Libraries
    runtimeOnly 'org.postgresql:postgresql'
    implementation 'org.hibernate.orm:hibernate-spatial'
    implementation 'org.locationtech.jts:jts-core:1.19.0'
}

tasks.named('test') {
    useJUnitPlatform()
}

def envFile = file('.env')
if (envFile.exists()) {
    envFile.readLines().each { line ->
        if (line.trim().length() > 0 && !line.startsWith("#")) {
            def parts = line.split("=", 2)
            if (parts.length == 2) {
                def key = parts[0].trim()
                def value = parts[1].trim()
                
                // Inject env vars into Gradle Test tasks
                tasks.withType(Test).configureEach {
                    environment key, value
                }
                // Inject env vars into bootRun
                tasks.withType(JavaExec).configureEach {
                    environment key, value
                }
            }
        }
    }
}
